### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by yize** [tinglejs/tingle-on-off#2]
1. dist 目录，应该删掉
2. README 中，注意下高亮
   
   ``````
   需要加入 ```js 类似的。
   ``````
3. 缺少 History.md 
4. README 中，on 的默认值应该是 `true`

**Comment by gbk** [comment]
on 定义为 required 的话，默认值就不给啦。

History.md 格式是否约定一下，按 [arale 的规范](https://github.com/aralejs/aralejs.org/wiki/%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95%E4%B9%A6%E5%86%99%E8%A7%84%E8%8C%83)来？

其余已经 fixed。

**Comment by yize** [comment]
我安装了 `git-extra` 。
通过 `git changelog` 生成的。 `NEW`,`FIXED` 这些可以按照他们的来。
建议在脚手架中新增 History.md

**Comment by yize** [comment]
tinglejs/generator-tingle#13
